#cloud-config
hostname: stable01.docker.howard.estate
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCp960By9RvYJdgsGBNQv4D4RTmIWYrn8PwdSFqadCYBw6eKVVLWssLo0zybZbDecNfkYNbkWQUdYvLWyw51s96qkWyX/mZA2ENtqO6zBasbkUac+XqU9SAAoX2dCZpuJpEtVWHInPcKHkve4ZwG//sCjy6/keRoZhfZWwA4dJhV3CPS5DXxW0i6taasLA7KkMwfjqSC2lNLiDftRuwdVMuPF+aqJLaR8LyryMqvz3fPRL8KOCB1CkrnL4+q5cBim8Pygw9lUnOp5On9wKP3uOR63C+lwtO6Db1gwekNcY3p6QVaMeU75bgNOmPCUv/O+xNODYR/8B/1dplR5yyQHApD4HvJJ7lyLjbKAEwXW12s3+3iqhhdIH1V8RW1f87ZocD44GrPHtPShemnd/8aKUfbM5J3bQC9w78hBTDxSFEMTXK8bS6I1hPwXDbWeSDQ4T9kLoChx93+95xu1tdTjecwSgaG0tQMGaG+xrke6Q9CTI8voZHt2tlkrxi93QD2JWSUSSUknrA4/K18hGjpeJKbxZsodufWd5E0B/HRgxdeZmcMwgNmka1RHDluevB9ajj0f7mxpz5VFNTtUfyIckW7EUiGxDKyctSw8LHOEOd1Wg8oe+SHzIZUdhm/OojEiQDmvUc5LkIszSA5VMdUokx6wmho+fHFbIKYgd5ql25xQ==

rancher:
  docker:
    extra_args: ['-H', 'tcp://0.0.0.0:2375']
  services_include:
    volume-cifs: true
