---
- hosts: localhost
  become: yes
  become_user: "{{params.vm_username}}"
  roles:
    - handcraftedbits/basic
    - handcraftedbits/secured
    - handcraftedbits/docker
    - handcraftedbits/infrastructure
    - handcraftedbits/docker-host