---
- hosts: localhost
  become: yes
  roles:
    - role: handcraftedbits/vm_basic
      vm_basic_github_id: "{{params.github_id}}"
      vm_basic_hostname: "{{params.vm_hostname}}"
      vm_basic_iptables_extra_ports: "{{params.vm_extra_ports}}"
      vm_basic_iptables_extra_ports_udp: "{{params.vm_extra_ports_udp}}"
      vm_basic_password: "{{params.vm_password}}"
      vm_basic_ssh_port: "{{params.vm_ssh_port}}"
      vm_basic_user_fullname: "{{params.vm_user_fullname}}"
      vm_basic_username: "{{params.vm_username}}"
    - role: handcraftedbits/s3_clone
      s3_clone_aws_access_key: "{{params.aws_access_key}}"
      s3_clone_aws_access_key_id: "{{params.aws_access_key_id}}"
      s3_clone_aws_region: "{{params.aws_region}}"
      s3_clone_buckets:
        - { name: "hcb-critical", path: "critical", hour: "3", minute: "0" }
        - { name: "hcb-media", path: "media", hour: "3", minute: "10" }
        - { name: "hcb-misc", path: "misc", hour: "3", minute: "15" }
      s3_clone_password: "{{params.vm_password}}"
      s3_clone_username: "{{params.vm_username}}"
    - role: handcraftedbits/samba_host
      samba_host_hostname: "{{params.vm_hostname}}"
      samba_host_password: "{{params.vm_password}}"
      samba_host_username: "{{params.vm_username}}"