---
- name: (ssh) add authorized keys
  authorized_key:
    exclusive: yes
    key: "{{ publickey }}"
    user: "{{ username }}"

- name: (ssh) update sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  with_items:
    - { regexp: "^Port", line: "Port {{ ssh_port }}" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }