version: "2.1"

services:
  samba:
    image: dperson/samba
    environment:
      - GROUPID=${SAMBA_GROUP_ID}
      - USERID=${SAMBA_USER_ID}
    command: >
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -s "critical;/shares/critical;yes;no;no;${SAMBA_USERNAME}"
      -s "media;/shares/media;yes;no;no;${SAMBA_USERNAME}"
      -s "misc;/shares/misc;yes;no;no;${SAMBA_USERNAME}" -n
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    network_mode: "host"
    restart: always
    volumes:
      - /shares/critical:/shares/critical
      - /shares/media:/shares/media
      - /shares/misc:/shares/misc