version: "2.1"

services:
  samba:
    image: dperson/samba
    environment:
      - GROUPID=${SAMBA_GROUP_ID}
      - USERID=${SAMBA_USER_ID}
    command: >
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -s "critical;/s3/critical;yes;no;no;${SAMBA_USERNAME}"
      -s "media;/s3/media;yes;no;no;${SAMBA_USERNAME}"
      -s "misc;/s3/misc;yes;no;no;${SAMBA_USERNAME}" -n
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    network_mode: "host"
    restart: always
    volumes:
      - /s3/critical:/s3/critical
      - /s3/media:/s3/media
      - /s3/misc:/s3/misc