---
- name: (fish) add apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:fish-shell/release-2

- name: (fish) install package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - fish

- name: (fish) change default user shell to Fish
  user:
    comment: "{{ user_full_name }}"
    name: "{{ username }}"
    shell: /usr/bin/fish

- name: (fish) create configuration directory
  file:
    path: /home/{{ username }}/{{ item }}
    state: directory
  with_items:
    - .config/fish

- name: (fish) link dotfile
  file:
    dest: /home/{{ username }}/{{ item.dest }}
    src: /home/{{ username }}/.cloned-repos/dotfiles/{{ item.src }}
    state: link
  with_items:
    - { src: "fish/config.fish", dest: ".config/fish/config.fish" }