---
- name: (main) set hostname
  hostname:
    name: "{{ hostname }}"

- name: (main) create default user group
  group:
    name: "{{ username }}"
    state: present

- name: (main) create default user
  user:
    append: yes
    group: "{{ username }}"
    groups: sudo
    name: "{{ username }}"
    password: "{{ password }}"
    state: present

- name: (main) add swap space
  shell: |
    fallocate -l {{ swap }} /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    echo "/swapfile none swap sw 0 0" | tee -a /etc/fstab
  when: swap is defined and swap != ""

- name: (main) update all dependencies
  apt:
    update_cache: yes
    upgrade: dist

- name: (main) clone dotfiles
  git:
    dest: /home/{{ username }}/.cloned-repos/dotfiles
    repo: https://github.com/handcraftedbits/dotfiles.git

- include: fish.yml
- include: misc.yml
- include: vim.yml

- name: (main) fix home directory permissions
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: /home/{{ username }}
    recurse: yes
    state: directory
