---
- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: create default user group
  group:
    name: "{{ username }}"
    state: present

- name: create default user
  user:
    append: yes
    group: "{{ username }}"
    groups: sudo
    name: "{{ username }}"
    password: "{{ password }}"
    state: present

- name: add swap space
  shell: fallocate -l {{ swap }} /swapfile && chmod 600 /swapfile && mkswap /swapfile && echo "/swapfile none swap sw 0 0" | tee -a /etc/fstab
  when: swap is defined and swap != ""

- name: update all dependencies
  apt:
    update_cache: yes
    upgrade: dist

- name: add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:fish-shell/release-2
    - ppa:neovim-ppa/unstable

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - exuberant-ctags
    - fish
    - git
    - man-db
    - neovim
    - p7zip-full
    - rar
    - unrar
    - unzip
    - zip

- name: clone dotfiles
  git:
    dest: /home/{{ username }}/.cloned-repos/dotfiles
    repo: https://github.com/handcraftedbits/dotfiles.git

- name: change default user shell to Fish
  user:
    comment: "{{ user_full_name }}"
    name: "{{ username }}"
    shell: /usr/bin/fish

- name: create configuration directories
  file:
    path: /home/{{ username }}/{{ item }}
    state: directory
  with_items:
    - .config/fish
    - .config/nvim
    - .tmux

- name: link dotfiles
  file:
    dest: /home/{{ username }}/{{ item.dest }}
    src: /home/{{ username }}/.cloned-repos/dotfiles/{{ item.src }}
    state: link
  with_items:
    - { src: "fish/config.fish", dest: ".config/fish/config.fish" }
    - { src: "tmux/molokai.conf", dest: ".tmux/molokai.conf" }
    - { src: "tmux/.tmux.conf", dest: ".tmux.conf" }
    - { src: "vim/.vimrc", dest: ".vimrc" }
    - { src: "vim/.vimrc", dest: ".config/nvim/init.vim" }

- name: link Neovim configuration directory
  file:
    dest: /home/{{ username }}/.vim
    src: /home/{{ username }}/.config/nvim
    state: link

- name: install Vundle
  git:
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim
    repo: https://github.com/VundleVim/Vundle.vim.git

- name: install Vundle plugins
  shell: HOME=/home/{{ username }} vim -c VundleUpdate -c quitall > /dev/null

- name: fix home directory permissions
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: /home/{{ username }}
    recurse: yes
    state: directory

- name: update Vim alternatives
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - { name: "editor", path: "/usr/bin/nvim" }
    - { name: "vi", path: "/usr/bin/nvim" }
    - { name: "vim", path: "/usr/bin/nvim" }
