---
- name: (misc) install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - man-db
    - p7zip-full
    - rar
    - unrar
    - unzip
    - zip

- name: (misc) create configuration directories
  file:
    path: /home/{{ username }}/{{ item }}
    state: directory
  with_items:
    - .tmux

- name: (misc) link dotfiles
  file:
    dest: /home/{{ username }}/{{ item.dest }}
    src: /home/{{ username }}/.cloned-repos/dotfiles/{{ item.src }}
    state: link
  with_items:
    - { src: "tmux/molokai.conf", dest: ".tmux/molokai.conf" }
    - { src: "tmux/.tmux.conf", dest: ".tmux.conf" }

