---
- hosts: localhost
  become: yes
  roles:
    - role: handcraftedbits/vm_basic
      vm_basic_github_id: "{{params.github_id}}"
      vm_basic_hostname: "{{params.vm_hostname}}"
      vm_basic_password: "{{params.vm_password}}"
      vm_basic_ssh_port: "{{params.vm_ssh_port}}"
      vm_basic_user_fullname: "{{params.vm_user_fullname}}"
      vm_basic_username: "{{params.vm_username}}"
    - role: handcraftedbits/aws
      aws_access_key: "{{params.aws_access_key}}"
      aws_access_key_id: "{{params.aws_access_key_id}}"
      aws_region: "{{params.aws_region}}"
      aws_password: "{{params.vm_password}}"
      aws_username: "{{params.vm_username}}"
    - role: handcraftedbits/github
      github_id: "{{params.github_id}}"
      github_password: "{{params.vm_password}}"
      github_username: "{{params.vm_username}}"
    - role: handcraftedbits/emacs
      emacs_password: "{{params.vm_password}}"
      emacs_username: "{{params.vm_username}}"
    - role: handcraftedbits/gpg
      gpg_key: "{{params.gpg_key}}"
      gpg_password: "{{params.vm_password}}"
      gpg_username: "{{params.vm_username}}"
    - role: handcraftedbits/vscode
      vscode_password: "{{params.vm_password}}"
      vscode_username: "{{params.vm_username}}"
    - role: handcraftedbits/xfce
      xfce_password: "{{params.vm_password}}"
      xfce_username: "{{params.vm_username}}"
    - role: handcraftedbits/docker
      docker_password: "{{params.vm_password}}"
      docker_username: "{{params.vm_username}}"
    - role: handcraftedbits/git
      git_email: "{{params.git_email}}"
      git_name: "{{params.git_name}}"
      git_password: "{{params.vm_password}}"
      git_username: "{{params.vm_username}}"
    - role: handcraftedbits/go
      go_password: "{{params.vm_password}}"
      go_username: "{{params.vm_username}}"
    - role: handcraftedbits/gopass
      gopass_password: "{{params.vm_password}}"
      gopass_ssh_key_id: "{{params.gopass_ssh_key_id}}"
      gopass_username: "{{params.vm_username}}"
    - role: handcraftedbits/hugo
    - role: handcraftedbits/java
      java_password: "{{params.vm_password}}"
      java_username: "{{params.vm_username}}"
    - role: handcraftedbits/nodejs
      nodejs_extra_tools:
        - bower
        - gulp-cli
        - http-server
      nodejs_password: "{{params.vm_password}}"
      nodejs_username: "{{params.vm_username}}"
    - role: handcraftedbits/packer
    - role: handcraftedbits/vnc
      vnc_password: "{{params.vm_password}}"
      vnc_username: "{{params.vm_username}}"
    - role: handcraftedbits/dotfiles_relink
      dotfiles_relink_github_id: "{{params.github_id}}"
      dotfiles_relink_password: "{{params.vm_password}}"
      dotfiles_relink_username: "{{params.vm_username}}"

