---
- name: (emacs) add apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:kelleyk/emacs

- name: (emacs) install package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - emacs25

- name: (emacs) add configuration directory
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: /home/{{ username }}/.emacs.d
    state: directory

- name: (emacs) update dotfile links
  file:
    dest: /home/{{ username }}/{{ item.dest }}
    force: yes
    src: /opt/devel/projects/dotfiles/{{ item.src }}
    state: link
  with_items:
    - { src: "emacs/.emacs", dest: ".emacs" }
    - { src: "emacs/config.org", dest: ".emacs.d/config.org" }