---
- name: (git) set configuration
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: "user.email", value: "{{ git_email }}" }
    - { name: "user.name", value: "{{ git_name }}" }

- name: (git) move configuration
  shell: mv /root/.gitconfig /home/{{ username }}
