---
- name: (github) create temporary askpass script
  blockinfile:
    block: "echo '{{ github_key_passphrase }}'"
    create: yes
    dest: /tmp/askpass.sh
    marker: "#!/bin/sh\n"
    mode: "0777"

- name: (github) retrieve SSH host key
  shell: ssh-keyscan -t rsa github.com >> {{ item }}/.ssh/known_hosts
  with_items:
    - /home/{{ username }}
    - /root

- name: (github) retrieve projects
  uri:
    method: GET
    return_content: yes
    url: https://api.github.com/users/{{ github_id }}/repos
  register: projects

- name: (github) clone projects
  shell: DISPLAY=:0 SSH_ASKPASS=/tmp/askpass.sh setsid git clone --recursive {{ item.ssh_url }}
  args:
    chdir: "{{ path_projects }}"
  with_items:
    - "{{ projects.json }}"
  ignore_errors: yes

- name: (github) list root SSH configuration files
  shell: ls -1 /root/.ssh
  register: root_ssh_files

- name: (github) remove root SSH configuration files
  file:
    path: /root/.ssh/{{ item }}
    state: absent
  with_items: "{{ root_ssh_files.stdout_lines }}"
