---
- include: emacs.yml
- include: go.yml
- include: java.yml
- include: nodejs.yml
- include: ssh.yml
- include: github.yml
- include: git.yml
- include: packer.yml
- include: vnc.yml
- include: vscode.yml
- include: xfce.yml
- include: misc.yml