---
- name: (misc) add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - ppa:ansible/ansible

- name: (misc) configure Microsoft fonts
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/{{ item.name }}
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { name: "accepted-mscorefonts-eula", value: "true", vtype: "select" }
    - { name: "present-mscorefonts-eula", value: "", vtype: "note" }

- name: (misc) install Source Code Pro font
  unarchive:
    dest: /usr/local/share/fonts
    remote_src: yes
    src: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz

- name: (misc) install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ansible
    - maven
    - ttf-mscorefonts-installer

- name: (misc) update Fish configuration
  lineinfile:
    dest: /home/{{ username }}/.config/fish/config.fish
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  with_items:
    - { regexp: "^set -gx GOPATH", line: "set -gx GOPATH {{ path_go }}" }
    - { regexp: "^set -gx GOROOT", line: "set -gx GOROOT /usr/lib/go-{{ version_golang }}" }
    - { regexp: "^set -gx JAVA_HOME", line: "set -gx JAVA_HOME /usr/lib/jvm/java-{{ version_java }}-oracle" }
    - { regexp: "^set -gx PATH", line: "set -gx PATH $GOROOT/bin $GOPATH/bin $PATH" }

- name: (misc) update dotfile links
  file:
    dest: /home/{{ username }}/{{ item.dest }}
    force: yes
    src: /opt/devel/projects/dotfiles/{{ item.src }}
    state: link
  with_items:
    - { src: "tmux/molokai.conf", dest: ".tmux/molokai.conf" }
    - { src: "tmux/.tmux.conf", dest: ".tmux.conf" }
    - { src: "vim/.vimrc", dest: ".vimrc" }
    - { src: "vim/.vimrc", dest: ".config/nvim/init.vim" }

- name: (misc) fix permissions
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - /home/{{ username }}
    - /opt/devel
    - /usr/local/share/fonts