---

- name: (main) include basic role
  include_role:
    name: basic

- name: (main) include secured role
  include_role:
    name: secured

- name: (main) include docker role
  include_role:
    name: docker

- name: (main) create Docker host directory
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: /opt/vm
    state: directory

- name: (main) copy Docker host configuration
  copy:
    dest: /opt/vm
    group: "{{ username }}"
    owner: "{{ username }}"
    src: "{{ host_dir }}"

- name: (main) start Docker services
  shell: docker-compose up -d
  args:
    chdir: /opt/vm/{{ hostname }}
  environment:

- name: (main) stop Docker services
  shell: docker-compose stop
  args:
    chdir: /opt/vm/{{ hostname }}